% Definite Clause Grammars

% A language generated by a grammar consists of all the string that
% the grammar classifies as grammatical.

% A context free recognizer tells us if a string belongs to the language
% generated by the context free grammar.

% A context free parser is a program which correctly decides whether a string
% belongs to the language generated by a context free grammar and tells us what
% its structure is.

% Context free languages are the languages that can be developed from context
% free grammars. 

% CFG Recognition Using Append

% Recognizers are defined in prolog by creating clauses that correspond to 
% grammar rules.
